apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"server"},"name":"server","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"server"}},"template":{"metadata":{"labels":{"app":"server"}},"spec":{"containers":[{"env":[{"name":"GOOGLE_APPLICATION_CREDENTIALS","value":"/etc/firebase/firebase.json"},{"name":"PORT","value":"80"},{"name":"INFURA_PROJECT_ID","valueFrom":{"secretKeyRef":{"key":"infuraId","name":"server-credentials"}}},{"name":"INFURA_PROJECT_SECRET","valueFrom":{"secretKeyRef":{"key":"infuraSecret","name":"server-credentials"}}}],"image":"ghcr.io/crate-network/server:latest","name":"server","ports":[{"containerPort":80}],"resources":{},"volumeMounts":[{"mountPath":"/etc/firebase","name":"auth-cred-volume","readOnly":true}]}],"imagePullSecrets":[{"name":"ghcr"}],"volumes":[{"name":"auth-cred-volume","secret":{"items":[{"key":"googleApplicationCredentials","path":"firebase.json"}],"secretName":"server-credentials"}}]}}}}
  creationTimestamp: "2022-05-01T03:33:41Z"
  generation: 3
  labels:
    app: server
  name: server
  namespace: default
  resourceVersion: "10250407"
  uid: 16568a10-3e57-46fc-8c10-c8cfe1b87370
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
        - env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/firebase/firebase.json
            - name: PORT
              value: "80"
            - name: INFURA_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: infuraId
                  name: server-credentials
            - name: INFURA_PROJECT_SECRET
              valueFrom:
                secretKeyRef:
                  key: infuraSecret
                  name: server-credentials
          image: ghcr.io/crate-network/server:latest
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/firebase
              name: auth-cred-volume
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ghcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: auth-cred-volume
          secret:
            defaultMode: 420
            items:
              - key: googleApplicationCredentials
                path: firebase.json
            secretName: server-credentials
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-05-01T03:33:41Z"
      lastUpdateTime: "2022-05-01T03:39:34Z"
      message: ReplicaSet "server-959979cc5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-06-29T22:44:56Z"
      lastUpdateTime: "2022-06-29T22:44:56Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
