/* tslint:disable */
/* eslint-disable */
/**
 * Crate Network API
 * ## About this spec  The Crate API exposes several endpoints which allows the Crate macOS, iOS,  iPadOS and web clients to interact with Crate\'s IPFS cluster without the  clients needing to run IPFS clients of their own. Crate Network implements  the IPFS Pinning API specification at the `/pins` endpoint, as described by  the spec found [on GitHub](https://github.com/ipfs/pinning-services-api-spec/blob/3196b0b466752a3626b716969703cbd48cb9bcf7/ipfs-pinning-service.yaml).  The pinning API accepts a Bearer authorization token retrieved from your Crate account. This identifies your user and adds the pinned content to  your files on Crate. This version of the API is modified to include  metadata, all of which is optional so that Crate continues to conform to  the IPFS spec.  The Filecoin replication service is handled via the pinning API. Instead of  using expensive, centralized cloud storage as the backend, Crate safely  replicates content onto other decentralized networks. When a request comes  to the pinning service to retrieve the content, Crate will prioritize  cached content, otherwise falling back to the Filecoin network to retrieve your files. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PinMeta,
    PinMetaFromJSON,
    PinMetaFromJSONTyped,
    PinMetaToJSON,
} from './PinMeta';

/**
 * Pin object
 * @export
 * @interface Pin
 */
export interface Pin {
    /**
     * Content Identifier (CID) to be pinned recursively
     * @type {string}
     * @memberof Pin
     */
    cid: string;
    /**
     * Optional name for pinned data; can be used for lookups later
     * @type {string}
     * @memberof Pin
     */
    name?: string;
    /**
     * Optional list of multiaddrs known to provide the data; see Provider Hints in the docs
     * @type {Set<string>}
     * @memberof Pin
     */
    origins?: Set<string>;
    /**
     * 
     * @type {PinMeta}
     * @memberof Pin
     */
    meta?: PinMeta;
}

/**
 * Check if a given object implements the Pin interface.
 */
export function instanceOfPin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cid" in value;

    return isInstance;
}

export function PinFromJSON(json: any): Pin {
    return PinFromJSONTyped(json, false);
}

export function PinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cid': json['cid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'origins': !exists(json, 'origins') ? undefined : json['origins'],
        'meta': !exists(json, 'meta') ? undefined : PinMetaFromJSON(json['meta']),
    };
}

export function PinToJSON(value?: Pin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cid': value.cid,
        'name': value.name,
        'origins': value.origins,
        'meta': PinMetaToJSON(value.meta),
    };
}

