/* tslint:disable */
/* eslint-disable */
/**
 * Crate Network API
 * ## About this spec  The Crate API exposes several endpoints which allows the Crate macOS, iOS,  iPadOS and web clients to interact with Crate\'s IPFS cluster without the  clients needing to run IPFS clients of their own. Crate Network implements  the IPFS Pinning API specification at the `/pins` endpoint, as described by  the spec found [on GitHub](https://github.com/ipfs/pinning-services-api-spec/blob/3196b0b466752a3626b716969703cbd48cb9bcf7/ipfs-pinning-service.yaml).  The pinning API accepts a Bearer authorization token retrieved from your Crate account. This identifies your user and adds the pinned content to  your files on Crate. This version of the API is modified to include  metadata, all of which is optional so that Crate continues to conform to  the IPFS spec.  The Filecoin replication service is handled via the pinning API. Instead of  using untrusted centralized cloud storage as the backend, Crate safely  replicates content onto other decentralized networks. When a request comes  to the pinning service to retrieve the content, Crate will prioritize  cached content, otherwise falling back to the Filecoin network to retrieve your files. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PinStatus,
    PinStatusFromJSON,
    PinStatusFromJSONTyped,
    PinStatusToJSON,
} from './PinStatus';

/**
 * Response used for listing pin objects matching request
 * @export
 * @interface PinResults
 */
export interface PinResults {
    /**
     * The total number of pin objects that exist for passed query filters
     * @type {number}
     * @memberof PinResults
     */
    count: number;
    /**
     * An array of PinStatus results
     * @type {Set<PinStatus>}
     * @memberof PinResults
     */
    results: Set<PinStatus>;
}

/**
 * Check if a given object implements the PinResults interface.
 */
export function instanceOfPinResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PinResultsFromJSON(json: any): PinResults {
    return PinResultsFromJSONTyped(json, false);
}

export function PinResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PinResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'results': (new Set((json['results'] as Array<any>).map(PinStatusFromJSON))),
    };
}

export function PinResultsToJSON(value?: PinResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'results': (Array.from(value.results as Set<any>).map(PinStatusToJSON)),
    };
}

