# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-in-progress
  labels:
    app: web-in-progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-in-progress
  template:
    metadata:
      labels:
        app: web-in-progress
    spec:
      containers:
      - name: web-in-progress
        image: ghcr.io/crate-network/web-inprogress:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr
---
# SERVICE SETUP
apiVersion: v1
kind: Service
metadata:
  name: web-in-progress
spec:
  selector:
    app: web-in-progress
  ports:
  - port: 80
    targetPort: 80