apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The Crate server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for Crate registration
    email: chris.vanderloo@yahoo.com
    # Name of a secret used to store the Crate account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx