name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Save package version to environment
      uses: nyaa8/package-version@v1.0.3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        platforms: linux/arm64/v8,linux/amd64
        tags: ghcr.io/crate-network/server:latest,ghcr.io/crate-network/server:${{ env.PACKAGE_VERSION }}
        push: true
