name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: package-version
      uses: nyaa8/package-version@v1.0.3
    - uses: joutvhu/write-file@v1
      with:
        path: .firebase.json
        contents: ${{ secrets.FIREBASE_JSON }}
        write_mode: overwrite
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        tags: ghcr.io/crate-network/web:latest,ghcr.io/crate-network/web:${{ env.PACKAGE_VERSION }}
