name: Build Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "packages/web/.env.local"
          FILE_BASE64: ${{ secrets.WEB_ENV }}
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "packages/server/.env"
          FILE_BASE64: ${{ secrets.API_ENV }}
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "packages/server/firebase.json"
          FILE_BASE64: ${{ secrets.API_FIREBASE_JSON }}\
      - name: Install dependencies
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker images with Nx
        run: npx nx affected --target=version && npx nx affected --target=docker
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
