name: Build Web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Save package version to environment
        uses: nyaa8/package-version@v1.0.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push web image
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./web
          platforms: linux/arm64/v8,linux/amd64
          tags: ghcr.io/crate-network/web:latest,ghcr.io/crate-network/web:${{ env.PACKAGE_VERSION }}
          push: true
          build-args:
            VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }},
            VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }},
            VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }},
            VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }},
            VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }},
            VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }},
            VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
